import SupabaseProvider from "@/context/supabase-client-context";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SupabaseAuthProvider from "@/context/supabase-auth-context";
import SupabaseClientProvider from "@/context/supabase-client-context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "LinkTree Replica",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SupabaseClientProvider>
          <SupabaseAuthProvider>{children}</SupabaseAuthProvider>
        </SupabaseClientProvider>
      </body>
    </html>
  );
}
